server:
  port: 8282

spring:
  application:
    name: uj-gateway
  zipkin:
    base-url: ${ZIPKIN_SERVER_URI:http://localhost:9411}
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            - allowedOrigins:
                - "http://localhost:4200"
                - "http://angular:4200"
                - "172.22.64.138:8888" # Synology NAS IP
            - allowedMethods:
                - "GET"
                - "POST"
                - "PUT"
                - "DELETE"
                - "OPTIONS"
      routes:
        - id: uj-users
          uri: lb://uj-users
          predicates:
            - Path=/uj-users/**
          filters:
            - RewritePath=/uj-users/(?<path>.*), /$\{path}

management:
  endpoints:
    web:
      exposure:
        include: gateway

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URI:http://localhost:8761/eureka/}
