server:
  port: 8282

spring:
  application:
    name: uj-gateway
  zipkin:
    base-url: ${ZIPKIN_SERVER_URI:http://localhost:9411}
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins:
              - "http://localhost:4200"
              - "http://angular:4200"
              - "http://172.22.64.138:8888"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      routes:
        - id: uj-users
          uri: lb://uj-users
          predicates:
            - Path=/uj-users/**
          filters:
            - RewritePath=/uj-users/(?<path>.*), /$\{path}
        - id: uj-problems
          uri: lb://uj-problems
          predicates:
            - Path=/uj-problems/**
          filters:
            - RewritePath=/uj-problems/(?<path>.*), /$\{path}
        - id: uj-file-uploader
          uri: lb://uj-file-uploader
          predicates:
            - Path=/uj-file-uploader/**
          filters:
            - RewritePath=/uj-file-uploader/(?<path>.*), /$\{path}
management:
  endpoints:
    web:
      exposure:
        include: gateway

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URI:http://localhost:8711/eureka/}
