server:
  port: 8282

spring:
  application:
    name: ucb-judge-gateway
  cloud:
    config:
      import-check:
        enabled: false
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            - allowedOrigins:
                - "localhost:4200"
                - "172.22.64.138:8888" # Synology NAS IP
            - allowedMethods:
                - "GET"
                - "POST"
                - "PUT"
                - "DELETE"
                - "OPTIONS"
#      routes:
#        - id: ms-customer
#          uri: lb://ms-customer
#          predicates:
#            - Path=/ms-customer/**
#          filters:
#            - RewritePath=/ms-customer/(?<path>.*), /$\{path}
#        - id: ms-account
#          uri: lb://ms-account
#          predicates:
#            - Path=/ms-account/**
#          filters:
#            - RewritePath=/ms-account/(?<path>.*), /$\{path}
# automatic discovery of services
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: gateway

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8711/eureka/